### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by shriswissfed**

### CODE REVIEW

**Comment by perliedman** [comment]
Hi,
the work in the `develop` branch is not completed, and it isn't stable, so I'm not merging at this point.

**Comment by shriswissfed** [comment]
Hey Hope You're doing fine,
I have uploaded a js file.
1.It has been set with default route.I am able to get its distance.I have
used alert to display it.

2.I have also coded for calculating and displaying the distance when user
clicks.

3.but the problem is when the user drags the default markers' location on
map or changes the location by typing on search bar(start,end) ,I am not
able to get the route data(distance,time).

4.Can you help me to get distance as and when user drags the markers and
display them as alert.

Can you edit the code?

and a doubt in nested functions in javascript.
How to get out of the inner function(onMapClicks) and pass the control to
outer function(onMapClick).I have tried all possible things but i heard
that js functions running on browser cant be made to pass control.

1.In the file i have attached ,the functions work perfect but the route is
calculated after each click,instead i want to calculate route after every
two clicks.

2.Here the route is calculated between nth click and first click because
the control is going again and again to the inner functions.The first pair
of latlng(lat1,lng1) in L.route.control in inner function stays equal to
co-ordinates of 1stclick always.
so the route is calculated between 1st and 2nd,1st and 3rd,1st adn 4th n so
on.

3.For every odd click the outer function must be executed and every even
click inner function must be calculated.
so that route is calculated between 1st and 2nd,3rd and 4th n so on.

I have tried my best but not able to make it work.Need your help!!!

Thank you in advance!!!!!!

**Comment by perliedman** [comment]
Sorry, but this is really the wrong place to ask questions like these. Also, code you attach don't end up here.

My time to handle application specific questions like these (that is, things specific to _your_ application, not to LRM in general) is very limited unless I'm doing it as work (paid, in other words). My free time, as well as energy, is unfortunately too limited.

**Comment by shriswissfed** [comment]
Yea i know that,but it will be really helpful if just helped me in getting
route data after dragging.
Thanks for taking time to reply!!!

**Pull request closed without merging**
