### PR TITLE
Add OSRM for stych

### PR DESCRIPTION
**Pull request by zaidjamal-op**

### CODE REVIEW

**Comment by zaidjamal-op** [comment]
Add OSRM for stych

**Comment by zaidjamal-op** [comment]
Add OSRM for stych

**Comment by curtisy1** [comment]
Hey there @zaidjamal-op, thanks for wanting to contribute!

I have a few questions:
1. Did you intentionally close this, or should I review?
2. What is "Stych"? I can't find it on the internet, so I'm guessing it's some private project you're using?

**Comment by zaidjamal-op** [comment]
Hey 👋

I hope you are doing well

Yeah i intentionally closed the PR because i made changes for my personal
project but i am also working on it to add new features and try to create
some PR in future.

Thanks
Zaid Jamal

**Pull request closed without merging**
