### PR TITLE
L.Routing.Plan: add option showMarkers

### PR DESCRIPTION
**Pull request by leandropls**
L.Routing.Plan: add option showMarkers that when set to false won't add markers in map

### CODE REVIEW

**Comment by leandropls** [comment]
Use case: I want to create my own non-draggable markers that I control. Or I just want to show the red line.

**Comment by perliedman** [comment]
Hi and thanks for the PR!

I think at least part of this use case is already covered by the quite recently added option `createMarker`: this way, you can create whatever marker you need, draggable or not, and "own" it as well, of course.

The only part not supported, is not showing any markers at all. The currently implementation forces you to actually return a marker.

I'm a bit reluctant to just add a lot of options, so maybe we could work this out so that already existing `createMarker` can be used for this use case as well? For example, we could allow `createMarker` to return `null`, and just skip adding a marker in that case.

**Comment by leandropls** [comment]
@perliedman Yeah, your solution works. I think it's worth mentioning in the docs that's the standard way of doing it.

**Comment by perliedman** [comment]
Yes, good point. Updated code to allow falsy return value and added a note in the docs for `createMarker`.

**Pull request closed without merging**
