### PR TITLE
Possibility to specify routingOptions in Routing Control options

### PR DESCRIPTION
**Pull request by martinboehm**
Added possibility to specify routingOptions (my use case is to set allowUTurns: true) of the routing request initiated by the Routing.Control.

### CODE REVIEW

**Comment by perliedman** [comment]
Hi,
thanks for this. I can totally see the use case, and it should of course be possible to for example set the `allowUTurns` option externally.

However, it is my feeling that this would be better as an option in the `L.Routing.OSRM` class, rather than in the control: my idea is that options for the router should be set on the router rather than passed from the control, if it can be avoided.

This way, the `route` method in `L.Routing.OSRM` would extend its own options with the options passed to the method, and for example `allowUTurns` could be set on the router's options.

Does this make sense to you?

**Comment by martinboehm** [comment]
Hi,

your comment makes total sense. I moved the `routingOptions` to `L.Routing.OSRM`.

As `L.Routing.Control` options are passed to the default `L.Routing.OSRM` anyway, I did not even have to modify my code which uses `L.Routing.Control` after the change.

Thanks!

**Comment by perliedman** [comment]
Thanks again! :+1: 

I made some minor adjustments regarding priority of the options, I'm hoping this should work for you.

**Comment by martinboehm** [comment]
Thanks, your version is perfect!

It seems to me thought that you did not push to your master branch the built javascript files (in the dist folder), I had to build the version 2.5.0 from the sources.

**Pull request closed without merging**
