### PR TITLE
Update L.Routing.Localization.js

### PR DESCRIPTION
**Pull request by rsofista**
Added some missing keys for the Portuguese translation:
'merge' I don't know o how to translate properly.

### CODE REVIEW

**Comment by perliedman** [comment]
It's a tricky one to translate into swedish as well.

If it helps, I _think_ it means when two roads meet, but not at a crossing, but rather the lanes connect (or simply _merge_) into each other, like sometimes larger highways do.

**Comment by rsofista** [comment]
like this:
http://etc.usf.edu/clipart/68000/68083/68083_129_w4-1_c_lg.gif

**Comment by perliedman** [comment]
@rsofista yes, exactly!

**Comment by perliedman** [comment]
Thanks! Great with more language support!

**Pull request merged**
